name: Update Packages in Port

on:
  workflow_call:
    inputs:
      RUNTIME:
        required: true
        type: string
        default: docker
      MICROSERVICE_NAME:
        type: string
        required: true
    secrets:
      PORT_AUTH0_CLIENT_ID:
        required: true
      PORT_AUTH0_CLIENT_SECRET:
        required: true

jobs:
  update-microservices:
    name: "Run package.json scanner"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # we fetch depth 2 so we can check if package.json changed since last commit
          fetch-depth: 2
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: package.json
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # if package.json changed, run script    
      - name: Run scanner script
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        env:
          RUNTIME: ${{ inputs.RUNTIME }}
          PORT_CLIENT_ID: ${{ secrets.PORT_AUTH0_CLIENT_ID }}
          PORT_CLIENT_SECRET: ${{ secrets.PORT_AUTH0_CLIENT_SECRET }}
          MICROSERVICE_NAME: ${{ inputs.MICROSERVICE_NAME }}
        run: |
            pip install -r .github/scripts/scan_requirements.txt
            python .github/scripts/scan-yarn-lock.py 
